theme: jekyll-theme-minimal
title: [The title of your site]
description: [A short description of your site's purpose]
logo: https://user-images.githubusercontent.com/26959437/120764347-a3b91680-c54a-11eb-9a15-31bb2596b0db.png
